import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";
export const metadata = {
  title: "qReserve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
